AWSTemplateFormatVersion: 2010-09-09
Description: "Amazon Managed Blockchain Basic Initial Member Template"
Description: Deploys an EKS cluster with JFrog Artifactory into an existing VPC (qs-1q037efm3).
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - 01NetworkName
          - 02NetworkDescription
          - 03Edition
      - Label:
          default: Member configuration
        Parameters:
          - 04FirstMemberName
          - 05FirstMemberDescription
          - 06FirstMemberAdminUsername
          - 07FirstMemberAdminPassword
      - Label:
          default: Blockchain configuration
        Parameters:
          - 08ThresholdPercentage
          - 09ThresholdComparator
          - 10ProposalDurationInHours
          - 11AvailabilityZoneForPeerNode1
          - 12AvailabilityZoneForPeerNode2
          - 13AvailabilityZoneForPeerNode3
          - 14InstanceType
    ParameterLabels:
      01NetworkName:
        default: Network name
      02NetworkDescription:
        default: Network description          
      03Edition:
        default: Managed Blockchain edition
      04FirstMemberName:
        default: First member name
      05FirstMemberDescription:
        default: First member description
      06FirstMemberAdminUsername:
        default: First member user name
      07FirstMemberAdminPassword:
        default: First member password
      08ThresholdPercentage:
        default: Threshold percentage
      09ThresholdComparator:
        default: Threshold comparator
      10ProposalDurationInHours:
        default: Proposal duration
      11AvailabilityZoneForPeerNode1:
        default: Availability Zone 1
      12AvailabilityZoneForPeerNode2:
        default: Availability Zone 2
      13AvailabilityZoneForPeerNode3:
        default: Availability Zone 3
      14InstanceType:
        default: Instance type
Parameters:
  01NetworkName:
    AllowedPattern: "^[0-9a-zA-Z]+$"
    ConstraintDescription: "NetworkName must be alphanumeric."
    Description: "The name of your Amazon Managed Blockchain network"
    Type: String
  02NetworkDescription:
    Type: String
    Description: "An optional description of your network"
  03Edition:
    ConstraintDescription: Must be STARTER or STANDARD
    Default: STARTER
    AllowedValues:
      - STARTER
      - STANDARD
    Type: String
  04FirstMemberName:
    AllowedPattern: "^[0-9a-zA-Z]+$"
    ConstraintDescription: "FirstMemberName must be alphanumeric."
    Description: "The name of the first member in your Amazon Managed Blockchain network"
    Type: String
  05FirstMemberDescription:
    Type: String
    Description: "An optional description of your first member"
  06FirstMemberAdminUsername:
    AllowedPattern: '^[0-9a-zA-Z/]+$'
    ConstraintDescription: AdminUsername must contain only uppercase and lowercase letters and numbers.
    Description: The administrator username for the first member in your blockchain network.
    Type: String
  07FirstMemberAdminPassword:
    MinLength: 8
    MaxLength: 32
    AllowedPattern: "^(?!.*?['\"\\/ @])(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).*{8,32}$"
    ConstraintDescription: >-
      AdminPassword must be at least 8 characters long and must contain at least one
      uppercase character, one lowercase character, and one digit. It must not
      contain ', ", \, /, @ or spaces. It must not exceed 32 characters in length.
    Description: The password for the administrator of the first member in your blockchain network.
    Type: String
    NoEcho: true
  08ThresholdPercentage:
    MinValue: 1
    MaxValue: 100
    Type: Number
    Default: 50
    Description: The percentage of favorable votes needed to approve a blockchain proposal
  09ThresholdComparator:
    ConstraintDescription: Must be GREATER_THAN or GREATER_THAN_OR_EQUAL_TO
    Default: GREATER_THAN
    AllowedValues:
      - GREATER_THAN
      - GREATER_THAN_OR_EQUAL_TO
    Type: String
    Description: >-
      This comparator is used to determine how the vote percentages are compared
      with the threshold. If it is GREATER_THAN, then the percentage of favorable
      votes must exceed the ThresholdPercentage for a proposal to pass. If it is
      GREATER_THAN_OR_EQUAL_TO, then the percentage of favorable votes must at
      least be equal to the threshold for a proposal to pass.
  10ProposalDurationInHours:
    MinValue: 1
    MaxValue: 168
    Default: 24
    Type: Number
    Description: "How many hours a proposal will last"
  11AvailabilityZoneForPeerNode1:
    Description: The availability zone that you want to deploy your first peer node in. As of 22-Aug-2019, only us-east-1a through us-east-1f are currently supported.
    Default: us-east-1a
    Type: String
  12AvailabilityZoneForPeerNode2:
    Description: The availability zone for your second peer node. Can be blank.
    Default: us-east-1b
    Type: String
  13AvailabilityZoneForPeerNode3:
    Description: The availability zone for your third peer node. Can be blank. A third peer node is only allowed in STANDARD edition.
    Type: String
  14InstanceType:
    Default: bc.t3.small
    Type: String
    AllowedValues:
      - bc.t3.small
      - bc.t3.medium
      - bc.t3.large
      - bc.t3.xlarge
      - bc.m5.large
      - bc.m5.xlarge
      - bc.m5.2xlarge
      - bc.m5.4xlarge
      - bc.c5.large
      - bc.c5.xlarge
      - bc.c5.2xlarge
      - bc.c5.4xlarge
    Description: >-
      If 03Edition is STARTER, then this value must be bc.t3.small
      or bc.t3.medium.

Conditions:
  CreatePeerNode2:
    !Not [!Equals [!Ref 12AvailabilityZoneForPeerNode2, '']]
  CreatePeerNode3:
    !Not [!Equals [!Ref 13AvailabilityZoneForPeerNode3, '']]
  HasNetworkDescription:
    !Not [!Equals [!Ref 02NetworkDescription, '']]
  HasFirstMemberDescription:
    !Not [!Equals [!Ref 05FirstMemberDescription, '']]

Resources:
  Member:
    Type: AWS::ManagedBlockchain::Member
    Properties:
      NetworkConfiguration:
        Name: !Ref 01NetworkName
        Description: !If [HasNetworkDescription, !Ref 02NetworkDescription, !Ref "AWS::NoValue"]
        Framework: HYPERLEDGER_FABRIC
        FrameworkVersion: "1.2"
        NetworkFrameworkConfiguration:
          NetworkFabricConfiguration:
            Edition: !Ref 03Edition
        VotingPolicy:
          ApprovalThresholdPolicy:
            ThresholdPercentage: !Ref 08ThresholdPercentage
            ProposalDurationInHours: !Ref 10ProposalDurationInHours
            ThresholdComparator: !Ref 09ThresholdComparator
      MemberConfiguration:
        Name: !Ref 04FirstMemberName
        Description: !If [HasFirstMemberDescription, !Ref 05FirstMemberDescription, !Ref "AWS::NoValue"]
        MemberFrameworkConfiguration:
          MemberFabricConfiguration:
            AdminUsername: !Ref 06FirstMemberAdminUsername
            AdminPassword: !Ref 07FirstMemberAdminPassword
  PeerNode1:
    Type: AWS::ManagedBlockchain::Node
    Properties:
      MemberId: !GetAtt Member.MemberId
      NetworkId: !GetAtt Member.NetworkId
      NodeConfiguration: 
        AvailabilityZone: !Ref 11AvailabilityZoneForPeerNode1
        InstanceType: !Ref 14InstanceType
  PeerNode2:
    Type: AWS::ManagedBlockchain::Node
    Condition: CreatePeerNode2
    Properties:
      MemberId: !GetAtt Member.MemberId
      NetworkId: !GetAtt Member.NetworkId
      NodeConfiguration: 
        AvailabilityZone: !Ref 12AvailabilityZoneForPeerNode2
        InstanceType: !Ref 14InstanceType
  PeerNode3:
    Type: AWS::ManagedBlockchain::Node
    Condition: CreatePeerNode3
    Properties:
      MemberId: !GetAtt Member.MemberId
      NetworkId: !GetAtt Member.NetworkId
      NodeConfiguration: 
        AvailabilityZone: !Ref 13AvailabilityZoneForPeerNode3
        InstanceType: !Ref 14InstanceType
